#!/usr/bin/env python3
"""
Agentic Collection – Rules Installer

Reads rules.json and merges permissions into each agent's config file.
Entries are written clean (no tags). On uninstall, the same entries are
recalculated from rules.json and removed by exact match.

Agent formats:
  Claude Code : ~/.claude/settings.json          → permissions.allow[] with Bash(pattern)
  Codex       : ~/.codex/rules/agentic.rules     → Starlark prefix_rule() declarations
  Gemini CLI  : ~/.gemini/settings.json           → tools.allowed[] with run_shell_command(prefix)
  OpenCode    : ~/.config/opencode/.opencode.json → permission.bash{} with pattern → "allow"
"""

import json
import sys
from pathlib import Path

PERMISSIONS_DIR = Path(__file__).resolve().parent
RULES_FILE = PERMISSIONS_DIR / "rules.json"

# ──────────────────────────────────────────────────────────────
# Agent config definitions
# ──────────────────────────────────────────────────────────────

AGENTS = {
    "Claude Code": {
        "config": Path.home() / ".claude" / "settings.json",
        "format": "claude",
    },
    "Codex": {
        "config": Path.home() / ".codex" / "rules" / "agentic.rules",
        "format": "codex",
    },
    "Gemini CLI": {
        "config": Path.home() / ".gemini" / "settings.json",
        "format": "gemini",
    },
    "OpenCode": {
        "config": Path.home() / ".config" / "opencode" / ".opencode.json",
        "format": "opencode",
    },
}

# ──────────────────────────────────────────────────────────────
# Helpers
# ──────────────────────────────────────────────────────────────

GREEN = "\033[0;32m"
RED = "\033[0;31m"
YELLOW = "\033[0;33m"
BOLD = "\033[1m"
DIM = "\033[2m"
RESET = "\033[0m"


def load_json(path: Path) -> dict:
    if path.exists():
        with open(path) as f:
            return json.load(f)
    return {}


def save_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")


def get_bash_patterns(rules: dict) -> list[str]:
    return rules.get("permissions", {}).get("bash", [])


def strip_wildcards(pattern: str) -> list[str]:
    """Strip leading */ and standalone * from a pattern, return non-empty tokens."""
    parts = []
    for token in pattern.split():
        if token == "*":
            continue
        cleaned = token.lstrip("*/")
        if cleaned:
            parts.append(cleaned)
    return parts


# ──────────────────────────────────────────────────────────────
# Claude Code
# permissions.allow[] with "Bash(pattern)"
# ──────────────────────────────────────────────────────────────


def claude_entries(rules: dict) -> list[str]:
    return [f"Bash({p})" for p in get_bash_patterns(rules)]


def claude_install(rules: dict, config_path: Path) -> int:
    entries = claude_entries(rules)
    config = load_json(config_path)
    permissions = config.setdefault("permissions", {})
    existing = permissions.get("allow", [])
    entries_set = set(entries)
    merged = [e for e in existing if e not in entries_set] + entries
    permissions["allow"] = merged
    save_json(config_path, config)
    return len(entries)


def claude_uninstall(rules: dict, config_path: Path) -> bool:
    if not config_path.exists():
        return False
    entries_set = set(claude_entries(rules))
    config = load_json(config_path)
    permissions = config.get("permissions", {})
    allow = permissions.get("allow", [])
    cleaned = [e for e in allow if e not in entries_set]
    if len(cleaned) == len(allow):
        return False
    permissions["allow"] = cleaned
    save_json(config_path, config)
    return True


def claude_status(rules: dict, config_path: Path) -> tuple[int, int]:
    if not config_path.exists():
        return -1, 0
    entries_set = set(claude_entries(rules))
    allow = load_json(config_path).get("permissions", {}).get("allow", [])
    managed = sum(1 for e in allow if e in entries_set)
    return managed, len(allow) - managed


# ──────────────────────────────────────────────────────────────
# Codex
# Standalone Starlark .rules file (no merge needed)
# ──────────────────────────────────────────────────────────────

CODEX_HEADER = "# Auto-generated by Agentic Collection. Do not edit.\n\n"


def codex_install(rules: dict, config_path: Path) -> int:
    patterns = get_bash_patterns(rules)
    lines = [CODEX_HEADER]
    for pattern in patterns:
        cmd_parts = strip_wildcards(pattern)
        if not cmd_parts:
            continue
        pattern_str = ", ".join(f'"{p}"' for p in cmd_parts)
        lines.append(f'prefix_rule(\n    pattern = [{pattern_str}],\n    decision = "allow",\n)\n\n')
    config_path.parent.mkdir(parents=True, exist_ok=True)
    with open(config_path, "w") as f:
        f.writelines(lines)
    return len(patterns)


def codex_uninstall(_rules: dict, config_path: Path) -> bool:
    if not config_path.exists():
        return False
    config_path.unlink()
    return True


def codex_status(_rules: dict, config_path: Path) -> tuple[int, int]:
    if not config_path.exists():
        return -1, 0
    with open(config_path) as f:
        count = f.read().count("prefix_rule(")
    return count, 0


# ──────────────────────────────────────────────────────────────
# Gemini CLI
# tools.allowed[] with "run_shell_command(prefix)"
# ──────────────────────────────────────────────────────────────


def gemini_entries(rules: dict) -> list[str]:
    entries = []
    seen = set()
    for pattern in get_bash_patterns(rules):
        parts = strip_wildcards(pattern)
        if not parts:
            continue
        cmd = " ".join(parts)
        if cmd not in seen:
            seen.add(cmd)
            entries.append(f"run_shell_command({cmd})")
    return entries


def gemini_install(rules: dict, config_path: Path) -> int:
    entries = gemini_entries(rules)
    config = load_json(config_path)
    tools = config.setdefault("tools", {})
    existing = tools.get("allowed", [])
    entries_set = set(entries)
    merged = [e for e in existing if e not in entries_set] + entries
    tools["allowed"] = merged
    save_json(config_path, config)
    return len(entries)


def gemini_uninstall(rules: dict, config_path: Path) -> bool:
    if not config_path.exists():
        return False
    entries_set = set(gemini_entries(rules))
    config = load_json(config_path)
    tools = config.get("tools", {})
    allowed = tools.get("allowed", [])
    cleaned = [e for e in allowed if e not in entries_set]
    if len(cleaned) == len(allowed):
        return False
    tools["allowed"] = cleaned
    save_json(config_path, config)
    return True


def gemini_status(rules: dict, config_path: Path) -> tuple[int, int]:
    if not config_path.exists():
        return -1, 0
    entries_set = set(gemini_entries(rules))
    allowed = load_json(config_path).get("tools", {}).get("allowed", [])
    managed = sum(1 for e in allowed if e in entries_set)
    return managed, len(allowed) - managed


# ──────────────────────────────────────────────────────────────
# OpenCode
# permission.bash{} with "pattern": "allow"
# ──────────────────────────────────────────────────────────────


def opencode_install(rules: dict, config_path: Path) -> int:
    keys = get_bash_patterns(rules)
    config = load_json(config_path)
    permission = config.setdefault("permission", {})
    bash = permission.get("bash", {})
    for key in keys:
        bash[key] = "allow"
    permission["bash"] = bash
    save_json(config_path, config)
    return len(keys)


def opencode_uninstall(rules: dict, config_path: Path) -> bool:
    if not config_path.exists():
        return False
    keys_set = set(get_bash_patterns(rules))
    config = load_json(config_path)
    permission = config.get("permission", {})
    bash = permission.get("bash", {})
    cleaned = {k: v for k, v in bash.items() if k not in keys_set}
    if len(cleaned) == len(bash):
        return False
    permission["bash"] = cleaned
    save_json(config_path, config)
    return True


def opencode_status(rules: dict, config_path: Path) -> tuple[int, int]:
    if not config_path.exists():
        return -1, 0
    keys_set = set(get_bash_patterns(rules))
    bash = load_json(config_path).get("permission", {}).get("bash", {})
    managed = sum(1 for k in bash if k in keys_set)
    return managed, len(bash) - managed


# ──────────────────────────────────────────────────────────────
# Dispatch
# ──────────────────────────────────────────────────────────────

HANDLERS = {
    "claude": (claude_install, claude_uninstall, claude_status),
    "codex": (codex_install, codex_uninstall, codex_status),
    "gemini": (gemini_install, gemini_uninstall, gemini_status),
    "opencode": (opencode_install, opencode_uninstall, opencode_status),
}


# ──────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────


def install(agent_names: list[str]) -> None:
    rules = load_json(RULES_FILE)
    if not rules:
        print(f"  {RED}✗{RESET} rules.json nicht gefunden")
        sys.exit(1)
    for name in agent_names:
        agent = AGENTS.get(name)
        if not agent:
            print(f"  {RED}✗{RESET} Unbekannter Agent: {name}")
            continue
        count = HANDLERS[agent["format"]][0](rules, agent["config"])
        print(f"  {GREEN}✓{RESET} {count} Regeln → {agent['config']}")


def uninstall(agent_names: list[str]) -> None:
    rules = load_json(RULES_FILE)
    if not rules:
        print(f"  {RED}✗{RESET} rules.json nicht gefunden")
        sys.exit(1)
    for name in agent_names:
        agent = AGENTS.get(name)
        if not agent:
            continue
        if HANDLERS[agent["format"]][1](rules, agent["config"]):
            print(f"  {RED}✗{RESET} {name} – Regeln entfernt")
        else:
            print(f"  {DIM}○ {name} – keine Regeln gefunden{RESET}")


def status() -> None:
    rules = load_json(RULES_FILE)
    for name, agent in AGENTS.items():
        managed, user = HANDLERS[agent["format"]][2](rules, agent["config"])
        if managed == -1:
            print(f"  {DIM}○ {name} – keine Config{RESET}")
        elif managed > 0:
            print(f"  {GREEN}●{RESET} {BOLD}{name}{RESET} – {managed} managed, {user} user-defined")
        elif user > 0:
            print(f"  {YELLOW}●{RESET} {BOLD}{name}{RESET} – 0 managed, {user} user-defined")
        else:
            print(f"  {DIM}○ {name} – keine Regeln{RESET}")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: install_rules.py <install|uninstall|status> [agent_names...]")
        sys.exit(1)

    action = sys.argv[1]
    agents = sys.argv[2:] if len(sys.argv) > 2 else list(AGENTS.keys())

    if action == "install":
        install(agents)
    elif action == "uninstall":
        uninstall(agents)
    elif action == "status":
        status()
    else:
        print(f"Unknown action: {action}")
        sys.exit(1)
